"""
Django settings for auth_django project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-63bvbh(#peli9stf5b*a1v8260#+=dc-d^^h198u__)fcvdc88'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ 'localhost', '127.0.0.1']
# 'myapi.canarytek.es',
SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'djangosaml2',
]

AUTHENTICATION_BACKENDS = ['djangosaml2.backends.Saml2Backend',]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'djangosaml2.middleware.SamlSessionMiddleware',
]

ROOT_URLCONF = 'auth_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            '/home/canarytek1/Escritorio/auth-saml/auth/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]




WSGI_APPLICATION = 'auth_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

# Configuración de SAML2
# SAML_CONFIG = {
#     # Llave privada de tu aplicación Django
#     'xmlsec_binary': '/usr/bin/xmlsec1',
#     'entityid': 'https://localhost:8000/saml2/metadata/',
#     'METADATA_LOCAL_FILE_PATH' : '/home/canarytek1/Escritorio/auth-django/saml',
#     'debug': True,
#     'service': {
#         'sp': {
#             'name': 'Django SAML2 Auth',
#             'endpoints': {
#                 # Configuración del endpoint de ACS
#                 'assertion_consumer_service': [
#                     ('http://localhost:8000/saml2/acs/', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'),
#                 ],
#             },
#             # Configuración del proveedor de identidad
#             'idp': {
#                 'entity_id': 'https://id.modularit.net',
#                 "singleSignOnService": [
#                     {
#                         "url": "https://id.modularit.net/application/saml/django-saml/sso/binding/redirect/",
#                         "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
#                     },
#                     {
#                         "url": "https://id.modularit.net/application/saml/django-saml/sso/binding/post/",
#                         "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#                     }
#                 ],
#                 "singleLogoutService": [
#                     {
#                         "url": "https://id.modularit.net/application/saml/django-saml/slo/redirect/",
#                         "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
#                     },
#                     {
#                         "url": "https://id.modularit.net/application/saml/django-saml/slo/post/",
#                         "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#                     }
#                 ],
#                  'x509cert': 'MIIGNjCCBR6gAwIBAgIQJTndOz05aEiRrinncwS7STANBgkqhkiG9w0BAQsFADCBjzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMB4XDTIyMTIxMjAwMDAwMFoXDTI0MDExMTIzNTk1OVowGjEYMBYGA1UEAwwPKi5tb2R1bGFyaXQubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4APaHENjI51nNKQXTH21wffCHR+qGp3WsOO/bdcsbdUyiN/OeV/WJNZdBcFCASOLeNhmOceABzlVpHO5XXkWLyNhKKUdX1EdMuJ+o1MCGadGDsCD2ckmFoIxo/ApDo5+fIdg6wMK7NJxUAk2M5Rkpcdly4PLhYcwEQOEJvmNrrI1n4aEPpVWZgUs5w12CmV1czSrs+TpY0wTkIBsaOKVbBceYSpFb/vGgvUhRqEs84TwM9Emb5ImMvGRmsOj9vibjGKumw5bDsKXpidSwO4QFMI3aQ9IoXBN+VpaAQdqSxiVPVZZ20FY0LbCHcBFXvuloR5hdqsgnQX6o7/ErDSZXwIDAQABo4IDADCCAvwwHwYDVR0jBBgwFoAUjYxexFStiuF36Zv5mwXhuAGNYeEwHQYDVR0OBBYEFDpanica2mo4kvGkBXrgWL6D0k4QMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysGAQQBsjEBAgIHMCUwIwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BTMAgGBmeBDAECATCBhAYIKwYBBQUHAQEEeDB2ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LnNlY3RpZ28uY29tL1NlY3RpZ29SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTApBgNVHREEIjAggg8qLm1vZHVsYXJpdC5uZXSCDW1vZHVsYXJpdC5uZXQwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB3AHb/iD8KtvuVUcJhzPWHujS0pM27KdxoQgqf5mdMWjp0AAABhQXoUekAAAQDAEgwRgIhAPHQMrStML0neU8V1tLYCI6pykaNdnyuUBF9Hg5UVlIzAiEAwoOQ/D5WoZCbHdmsur3p9Xbmlzf1n2S5IYVYDpFoNCAAdgA7U3d1Pi25gE6LMFsG/kA7Z9hPw/THvQANLXJv4frUFwAAAYUF6FGdAAAEAwBHMEUCIHkNxSP8CiiM19ohq7mfTh60GfDn6pIJsnYtopD3kwITAiEA7t0ARmFQDq6hUpgBxRDS3GYvYxS82cVH/pLcWGJhgdgAdQDuzdBk1dsazsVct520zROiModGfLzs3sNRSFlGcR+1mwAAAYUF6FGgAAAEAwBGMEQCIEctqbRvRiW35o8fOFSA8BA9z/RSapR8MT3dbmkRHHl7AiBlmz/I6COL+o3q+umlMdWwf5X1PrjhUHh//BUTlYjAWzANBgkqhkiG9w0BAQsFAAOCAQEAARx7xgIMC7ggShy4pGDi+VjvhPu6+mKisBwdWKPF1oiH0QQ+H4hEgJ6wiMAG+WXuQjOa/NGxR7DJ9kK1zNw8EwO9bkvUUUcFNSOdacKRe+8Am9AiD1zo9SUTxboobpYxKA7BDOAkKX/Q0zdSNuxdGu5zV9+nDOJX1Egu2WAH7/1wd0DSp7RLzoxvgwaR/Fmx5PdP+HThxawonp3wzZldzOaqBs8UnYjrtdJxgh+GXAMxnfYiCcpr0IF2Gc2rdDE6BMiLRTvAY7VHCwaYQbCJ7d4YS6tnAF1MP0t9TCDUFbjaJTqtftn8bSvksWcioASMW5pqh0gTtyN9NFdhStXJZg==MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0plcnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNVBAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgxMTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+NTQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkjeocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0EoKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBskHaswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotYuK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0jBBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb+ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAwCAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2BggrBgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDovL29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/HukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGiH19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUxRP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLvxvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyALl6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhYLcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K00u/I5sUKUErmgQfky3xxzlIPK1aEn8=MIIFgTCCBGmgAwIBAgIQOXJEOvkit1HX02wQ3TE1lTANBgkqhkiG9w0BAQwFADB7MQswCQYDVQQGEwJHQjEbMBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYDVQQHDAdTYWxmb3JkMRowGAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UEAwwYQUFBIENlcnRpZmljYXRlIFNlcnZpY2VzMB4XDTE5MDMxMjAwMDAwMFoXDTI4MTIzMTIzNTk1OVowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBOZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAgBJlFzYOw9sIs9CsVw127c0n00ytUINh4qogTQktZAnczomfzD2p7PbPwdzx07HWezcoEStH2jnGvDoZtF+mvX2do2NCtnbyqTsrkfjib9DsFiCQCT7i6HTJGLSR1GJk23+jBvGIGGqQIjy8/hPwhxR79uQfjtTkUcYRZ0YIUcuGFFQ/vDP+fmyc/xadGL1RjjWmp2bIcmfbIWax1Jt4A8BQOujM8Ny8nkz+rwWWNR9XWrf/zvk9tyy29lTdyOcSOk2uTIq3XJq0tyA9yn8iNK5+O2hmAUTnAU5GU5szYPeUvlM3kHND8zLDU+/bqv50TmnHa4xgk97Exwzf4TKuzJM7UXiVZ4vuPVb+DNBpDxsP8yUmazNt925H+nND5X4OpWaxKXwyhGNVicQNwZNUMBkTrNN9N6frXTpsNVzbQdcS2qlJC9/YgIoJk2KOtWbPJYjNhLixP6Q5D9kCnusSTJV882sFqV4Wg8y4Z+LoE53MW4LTTLPtW//e5XOsIzstAL81VXQJSdhJWBp/kjbmUZIO8yZ9HE0XvMnsQybQv0FfQKlERPSZ51eHnlAfV1SoPv10Yy+xUGUJ5lhCLkMaTLTwJUdZ+gQek9QmRkpQgbLevni3/GcV4clXhB4PY9bpYrrWX1Uu6lzGKAgEJTm4Diup8kyXHAc/DVL17e8vgg8CAwEAAaOB8jCB7zAfBgNVHSMEGDAWgBSgEQojPpbxB+zirynvgqV/0DCktDAdBgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rIDZsswDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAGBgRVHSAAMEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwuY29tb2RvY2EuY29tL0FBQUNlcnRpZmljYXRlU2VydmljZXMuY3JsMDQGCCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMA0GCSqGSIb3DQEBDAUAA4IBAQAYh1HcdCE9nIrgJ7cz0C7M7PDmy14R3iJvm3WOnnL+5Nb+qh+cli3vA0p+rvSNb3I8QzvAP+u431yqqcau8vzY7qN7Q/aGNnwU4M309z/+3ri0ivCRlv79Q2R+/czSAaF9ffgZGclCKxO/WIu6pKJmBHaIkU4MiRTOok3JMrO66BQavHHxW/BBC5gACiIDEOUMsfnNkjcZ7Tvx5Dq2+UUTJnWvu6rvP3t3O9LEApE9GQDTF1w52z97GA1FzZOFli9d31kWTz9RvdVFGD/tSo7oBmF0Ixa1DVBzJ0RHfxBdiSprhTEUxOipakyAvGp4z7h/jnZymQyd/teRCBaho1+V',  # el certificado X.509 de tu IdP
#             },
#         },
#     },
# }



# SAML_CONFIG = {
#     'xmlsec_binary': '/usr/bin/xmlsec1',
#     'entityid': 'https://localhost:8000/saml2/metadata/',
#     'METADATA_LOCAL_FILE_PATH' : '/home/canarytek1/Escritorio/auth-django/saml',
#     'debug': True,
#     'service': {
#         'sp': {
#             'name': 'Django SAML2 Auth',
#             'endpoints': {
#                 'assertion_consumer_service': [
#                     ('http://localhost:8000/saml2/acs/', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'),
#                 ],
#             },
#             'idp': {
#                 'entity_id': 'https://id.modularit.net',
#                 "singleSignOnService": [
#                     {
#                         "url": "https://id.modularit.net/application/saml/django-saml/sso/binding/redirect/",
#                         "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
#                     },
#                     {
#                         "url": "https://id.modularit.net/application/saml/django-saml/sso/binding/post/",
#                         "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#                     }
#                 ],
#                 "singleLogoutService": [
#                     {
#                         "url": "https://id.modularit.net/application/saml/django-saml/slo/redirect/",
#                         "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
#                     },
#                     {
#                         "url": "https://id.modularit.net/application/saml/django-saml/slo/post/",
#                         "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#                     }
#                 ],
#         'x509cert': 'MIIGNjCCBR6gAwIBAgIQJTndOz05aEiRrinncwS7STANBgkqhkiG9w0BAQsFADCBjzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMB4XDTIyMTIxMjAwMDAwMFoXDTI0MDExMTIzNTk1OVowGjEYMBYGA1UEAwwPKi5tb2R1bGFyaXQubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4APaHENjI51nNKQXTH21wffCHR',
#         'privateKey': 'YOUR_SP_PRIVATE_KEY'
#     }
# }
#     }}


SAML2_AUTH = {
    'DEFAULT_NEXT_URL': '/',
    'ENTITY_ID': 'https://id.modularit.net/metadata',
    'NAME_ID_FORMAT': 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',
    'USE_JWT': False,
    'ASSERTION_URL': 'http://127.0.0.1:8000',
    'ENTITY_ID': 'https://id.modularit.net/metadata',
    'METADATA_LOCAL_FILE_PATH': '/home/canarytek1/Escritorio/auth-django/saml'
}
